config/routes.rb
MicroApp::Application.routes.draw do

  get "user_sessions/new"

  resources :users do
    resources :microposts
  end

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup

  root :to => 'users#new'
end

app/models/ability.rb
 class Ability
       include CanCan::Ability

                def initialize(user)
                  user ||= User.new # Guest
                  can :read, :all
                  if user.id
                      can :manage, Micropost, user_id: user.id
                      can :update, User, id: user.id
                  else
                      can :create, User
                  end
                end
              end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :resources, :user_id
  belongs_to :user
  validates :resources, :length => { maximum: 140}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  acts_as_authentic
  has_many :microposts
  	validates_presence_of :password, :message => "pick a shorter password"
  	validates_length_of :name	, within: 6..20, too_long: 'pick a shorter name', too_short: 'pick a longer name'
  	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, on: :create
  	validates_confirmation_of :name, :password
    validates_confirmation_of :email,
                              message: 'should match confirmation'
	validates_presence_of :password_confirmation, if: :password_changed?
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base



      def to_key

        new_record? ? nil : [ self.send(self.class.primary_key) ]

      end


      def persisted?

        false

      end

    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

      protect_from_forgery

      helper_method :current_user_session, :current_user

      before_filter :new_user_session

      private

      def current_user_session

        return @current_user_session if defined?(@current_user_session)

        @current_user_session = UserSession.find

      end

       

      def current_user

        return @current_user if defined?(@current_user)

        @current_user = current_user_session && current_user_session.record

      end


      def new_user_session

        @new_user_session = UserSession.new

      end

    end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  load_and_authorize_resource :user
  load_and_authorize_resource through: :user

  # GET /microposts
  # GET /microposts.json
  before_filter :get_user
  before_filter :get_micropost, only: [:show, :edit, :update, :destroy] 

  def index

    #@user = User.find(params[:user_id])
    #@microposts = Micropost.all
    @microposts = @user.microposts


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show

    #@user = User.find(params[:user_id])
    #@micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new

    #@user = User.find(params[:user_id])
    @micropost = Micropost.new(:user_id => @user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    #@user = User.find(params[:user_id])
    #@micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    
    #@user = User.find(params[:user_id])
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format| 
      if @micropost.save
        format.html { redirect_to [@user, @micropost], notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    
    #@micropost = Micropost.find(params[:id])
    #@user = User.find(params[:user_id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to [@user, @micropost], notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    #@user = User.find(params[:user_id])
    #@micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to user_microposts_path(@user) }
      format.json { head :no_content }
    end
  end

  def get_user
    @user = User.find(params[:user_id])
  end

    def get_micropost
    @micropost = Micropost.find(params[:id])
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController


      def new

        @user_session = UserSession.new

      end

      

      def create

        @user_session = UserSession.new(params[:user_session])

        if @user_session.save

          flash[:notice] = "Login successful!"

          # leve me aos micropost do user logado
          
          redirect_to user_microposts_path(current_user.id)

        else

          flash[:notice] = "Login error!"

          render :action => :new

        end

      end


      def destroy

        @user_session = UserSession.find

        @user_session.destroy

        flash[:notice] = "Successfully logged out."

        redirect_to "/"

      end


    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
#load_and_authorize_resource

# temporaio index
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def new

      @user = User.new

    end


    def edit

      @user = current_user

    end


    def create

      @user = User.new(params[:user])

      if @user.saveusers

        flash[:notice] = "Create successful!"

        redirect_to user_sessions_new_path

      else

        render :action => 'new'

      end

    end


    def update

      @user = current_user


      if @user.update_attributes params[:user]

        flash[:notice] = "Update successful!"

        redirect_to "/my_account"

      else

        render :action => :edit

      end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroApp</title>
  <%= stylesheet_link_tag "style" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" id="bran" href="#"><div id="logo"><%= image_tag("twitter.png", :alt => "Micro-Twitter", :width => 25) %>
      <% if !current_user.present? %>
      <%=link_to "Micro-Twitter", root_path, class: 'brand'%>
      <% else  %>
       <%=link_to "Micro-Twitter", user_microposts_path, class: 'brand'%>
      <% end %>
    </div></a>



    <ul class="nav">

      <li class="<%= 'active' if current_page?(user_sessions_new_path) %>">
        <% if !current_user.present? %>
        <%= link_to 'Sign in', user_sessions_new_path %> 
        <% else  %>
        <%= link_to 'Profile'%>
        <% end %>
      </li>

      <li class="<%= 'active' if (current_page?(new_user_path) or current_page?(root_path)) %>">
      <% if !current_user.present? %>
      <%= link_to 'Sign up', new_user_path %>
      <% else %> 
      <%= link_to 'Sign out', logout_path %>
      <% end %>
    </li>
    </ul>


  </div>
</div>

<center>
<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
  </div>
</div>
</center>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for([@user, @micropost]) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :resources %>
  </div>

 
    <%= f.hidden_field :user_id %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing <%=@user.name%>'s micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', user_micropost_path(@user, @micropost) %> |
<%= link_to 'Back', user_micropost_path(@user, @micropost) %>

app/views/microposts/index.html.erb
<h1><%=@user.name%>'s microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.resources %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', user_micropost_path(@user,micropost) %></td>
    <td><%= link_to 'Edit', edit_user_micropost_path(@user,micropost) %></td>
    <td><%= link_to 'Destroy', user_micropost_path(@user,micropost), method: :delete, data: { confirm: 'Are you sure?' } %></td>  
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_user_micropost_path(@user) %>

app/views/microposts/new.html.erb
<h1>New <%=@user.name%>'s micropost</h1>

<%= render 'form'%>

<%= link_to 'Back', user_microposts_path(@user) %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.resources %>
</p>

<p>
  <b>User:</b>
  <%= @user.name %>
</p>

<p>
  <b>Create at:</b>
  <%= @user.created_at %>
</p>

<%= link_to 'Edit', edit_user_micropost_path(@user, @micropost) %> |
<%= link_to 'Back', edit_user_micropost_path(@user, @micropost) %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
<h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
<ul>
<% target.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/user_sessions/new.html.erb
<h2>Sign in</h2>	<br><hr>
<%= form_for [@user_session], :html => { :class => 'form-inline' }, :as => :user_session, :url => { :action => "create" } do |f| %>
   <%= render "shared/error_messages", :target => @user_session %>


      <div class="control-group">
        <%= f.label :email, :class => "control-label", :for => "inputEmail" %>
        <div class="controls"> 
        <%= f.text_field :email, :class => "input-xlarge" , :id=> "inputEmail", :placeholder => "Enter email" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password, :class => "control-label", :for => "inputPassword" %>
        <div class="controls"> 
        <%= f.password_field :password, :class => "input-xlarge" , :id=> "inputPassword", :placeholder => "Enter password" %>
        </div>
      </div>

  <%= f.check_box :remember_me %><%= f.label :remember_me, :class => "checkbox"  %><br />
  <br />

      <%= button_tag( :class => "btn btn-info") do %>
        Login <i class="icon-user icon-white"></i>
      <% end %>
<hr>
<% end %>

app/views/users/_form.html.erb
 
 <%= form_for [@user], :html => { :class => 'form-horizontal' } do |f| %>

      <% if @user.errors.any? %>

        <div id="error_explanation">

          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>


          <ul>

          <% @user.errors.full_messages.each do |msg| %>

            <li><%= msg %></li>

          <% end %>

          </ul>

        </div>

      <% end %>


<hr>

      <div class="control-group">
         <%= f.label :username, :class => "control-label", :for => "inputEmail" %>
        <div class="controls">  
        <%= f.text_field :name, :class => "input-xlarge" ,:id=> "inputEmail", :placeholder => "Enter username"  %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :email, :class => "control-label", :for => "inputEmail" %>
        <div class="controls"> 
        <%= f.text_field :email, :class => "input-xlarge" , :id=> "inputEmail", :placeholder => "Enter email" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password, :class => "control-label", :for => "inputPassword" %>
        <div class="controls"> 
        <%= f.password_field :password, :class => "input-xlarge" , :id=> "inputPassword", :placeholder => "Enter password" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password_confirmation, :class => "control-label", :for => "inputPassword" %>
        <div class="controls"> 
        <%= f.password_field :password_confirmation, :class => "input-xlarge" , :id=> "inputPassword", :placeholder => "Enter password confirmation" %>
        </div>
      </div>

      <div class="actions">

        <%= f.submit "Create user", :class => 'btn btn-info' %>

      </div>

    <% end %>

app/views/users/edit.html.erb
  <h1>Editing user</h1>


      <%= render 'form' %>


      <%= link_to 'Show', @user %> |

      <%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%=l user.created_at %></td>
        <td>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>


          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<h2 class = "sign_up">Don't have an account?</h2>
 <%= render 'form' %>

app/views/users/show.html.erb
<p>
<b>Email:</b>
<%=h @user.email %>
</p>

<p>
<b>Login count:</b>
<%=h @user.login_count %>
</p>

<p>
<b>Last request at:</b>
<%=h @user.last_request_at %>
</p>

<p>
<b>Last login at:</b>
<%=h @user.last_login_at %>
</p>

<p>
<b>Current login at:</b>
<%=h @user.current_login_at %>
</p>

<p>
<b>Last login ip:</b>
<%=h @user.last_login_ip %>
</p>

<p>
<b>Current login ip:</b>
<%=h @user.current_login_ip %>
</p>

<%= link_to 'Edit Account', edit_account_path %>